### PR TITLE
[Iss355] updated brighthub url

### PR DESCRIPTION
**Pull request by BiancaMorandi**
The following updates were made for `LoadBrightHub`:

1. Updated URL
2. Updated `_get_id_token` function to don't use `boto3`. This function was also updated to return specific errors depending on the response. 
3. Updated method to get id_token  only once
4. Added `_brighthub_refresh_token` function to return a new token if the current id_token has expired.  This function will return specific errors depending on the response
5. Added generic function `_brighthub_request` to make a GET request to the Brighthub endpoints
6. Updated the following functions to use the generic `_brighthub_request` above:  `get_plants`, `get_measurement_stations`, `get_start_end_dates`, `get_data_model`, `get_data`, `get_chunk`
7. Added tests
8. Updated Changelog

### CODE REVIEW

**Comment by BiancaMorandi** [comment]
I made few additional updates today:

1. split the LoadBrightHub functions in two classes in order to do a single request for id_token and avoid making multiple get requests to BrightHub
2. removed duplicate request for getting start and end dated in `LoadBrightHub.get_data`

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi ,

If my BRIGHTHUB_EMAIL and password are not setup. Is an error thrown when I first `import brightwind as bw`? Can you test that please?

**Comment by BiancaMorandi** [comment]
> Hi @BiancaMorandi ,
> 
> If my BRIGHTHUB_EMAIL and password are not setup. Is an error thrown when I first `import brightwind as bw`? Can you test that please?

Test done and issue fixed.

**Comment by stephenholleran** [comment]
@BiancaMorandi I made some edits and merged.

**Pull request merged**
