### PR TITLE
Iss15 add coverge to monthly means plot

### PR DESCRIPTION
**Pull request by Inder95**
@stephenholleran Added the coverage plot to monthly_means as described in iss #15. But if multiple series are passed it does not plot the coverage. I did because it would be make the graph useless because all the coverage bars would be at the same place on x-axis. Doing this would save the user from thinking that there is some problem with the code.

### CODE REVIEW

**Comment by stephenholleran** [comment]
Do you have a screen shot of the resulting plot using just a single wind speed variable? And more than one.

**Comment by Inder95** [comment]
For one variable

image

For more than one variable as I mentioned I avoided plotting coverage to prevent confusion

image

**Comment by stephenholleran** [comment]
Looks good.

Can you put units in for coverage [%] and capital 'C' for coverage? We should multiply by 100 as a  result?

What about the label on the left y-axis? Can we guess what is sent or have a default parameter set to 'Wind speed [m/s]'?

**Comment by stephenholleran** [comment]
As with the lower image we should possibly specify which anemometer is plotted e.g. Spd80mS. The image I pasted in #15 has the labels to the left but they could be overlaid like in image 2 here or put above the plot?

**Comment by Inder95** [comment]
> Looks good.
> 
> Can you put units in for coverage [%] and capital 'C' for coverage? We should multiply by 100 as a result?
> 
> What about the label on the left y-axis? Can we guess what is sent or have a default parameter set to 'Wind speed [m/s]'?

We are using coverage_threshold also with the range 0-1 hence converting to 5 from 0 - 100 might be confusing here. Coverage is ratio so no units might be fine here.

**Comment by Inder95** [comment]
@stephenholleran How does this look? I can resolve the  conflicting issues if you are fine with merging it.

image

**Comment by stephenholleran** [comment]
Its good. A few more suggestions to make it more complete.

1. Label for coverage 'Coverage [-]'

2. Make the coverage axis have a min and max of 0 and 1. I have a plot where there is no 100% coverage but the bars go right up to the top making it look like they have 100% coverage. There should be a gap hence setting the max to 1 should create this gap.

3. Make the min wind speed label set to 0. So it is consistent from one plot to the next.

4. Is it possible to add white space to the left of the first bar and to the right of the last bar. It looks a bit weird when there are only a few months in the plot.

**Comment by stephenholleran** [comment]
Also, your code in the screen shot above. That doesn't work for me and I wouldn't expect it to.

image

Not sure what `<class 'str'>` is?



This is how I would expect it to work and it does. How is yours working?

image

**Comment by Inder95** [comment]
> Also, your code in the screen shot above. That doesn't work for me and I wouldn't expect it to.
> 
> image
> 
> Not sure what `<class 'str'>` is?
> 
> This is how I would expect it to work and it does. How is yours working?
> 
> image

That print statement was for me checking something, didn't push it after I removed it.

**Comment by Inder95** [comment]
image

image

**Comment by stephenholleran** [comment]
It looks like there is no space after coverage and before the brackets. 

The x axis labels are not showing whole months in the second plot?

How is your code line showing a plot when a plot and data are returned?

**Pull request merged**
