### PR TITLE
[Iss317] fix ti by speed version issues

### PR DESCRIPTION
**Pull request by BiancaMorandi**
@stephenholleran As part of this pull request the issues below were fixed:

1. solved error raised by `TI.by_speed` when Pandas >= 1.3.3
    -  tests performed from Pandas=0.25.0 to Pandas=1.4.4 (and for different numpy versions) to confirm that issue is solved
3. added missing info in docstring of  `TI.by_speed` and  `TI.by_sector` (ie examples)
4. added missing tests for `TI.by_speed` and  `TI.by_sector`
5. fixed bug for `TI.by_speed` and  `TI.by_sector` when speed_bin_labels and direction_bin_labels, respectively, are given as input.
6. updated `TI.by_speed` to have as input `min_speed` and allow user to decide the minimum speed to use for deriving turbulence intensity - Note that min speed is excluded from the filter -> ie if min_speed =3 then x >= 3 m/s are data used for TI calculation
7. Fixed bug for  `TI.by_sector` where `min_speed` input was actually not used for filtering the turbulence intensity calculation as would have been expected
8. Fixed bug for `TI.by_speed` for IEC_class input. If IEC_class input was different than None then the `plot_TI_by_speed` function was giving an error as not able to plot IEC_class inputs different than the default

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hey @BiancaMorandi 

I am getting this error when running TI.by_sector. I am using the demo data with no cleaning.
image

Versions are:
brightwind	version: 2.1.0.dev	branch: iss317_fix_ti_by_speed_version
pandas		version: 1.3.3
numpy		version: 1.24.1

**Comment by stephenholleran** [comment]
I see you did a got bit on the 'min_speed' sent to the functions. If I use a 'min_speed' should it also reflect in the plot and not just the data? Below I used a 'min_speed' of 0.

image

Should the x-axis limit reduce down to 0 and then show all the dots?
Similarly if i use 5 as the min speed only the Mean TI and Rep TI get cut off at 5 m/s whereas all the dots are still shown on the plot down to 3 m/s.

image

**Comment by BiancaMorandi** [comment]
> Hey @BiancaMorandi
> 
> I am getting this error when running TI.by_sector. I am using the demo data with no cleaning. image
> 
> Versions are: brightwind version: 2.1.0.dev branch: iss317_fix_ti_by_speed_version pandas version: 1.3.3 numpy version: 1.24.1

solved

**Comment by BiancaMorandi** [comment]
@stephenholleran the two issues you raised above are solved now.

**Pull request merged**
